package.json, src/logql.grammar, src/tokens.js, test/expression.txt
Fixes: https://github.com/grafana/grafana/issues/49401
This PR:
1. In `DurationFilter` we need to use `Identifier` in the same way as it is used in https://github.com/grafana/loki/blob/main/pkg/logql/syntax/expr.y#L320
2. In `UnwrapExpr` the grammar should be `UnwrapExpr Pipe LabelFilter` instead of `Unwrap Pipe LabelFilter` as in https://github.com/grafana/loki/blob/main/pkg/logql/syntax/expr.y#L179
3. The conversion functions `duration`, `duration_seconds` and `bytes` are parsed only when used as functions.
I have also added and updated tests for these.
=> Parser: Fix unwrap with duration label

package.json, src/logql.grammar, tools/tree-viz.html
The current grammar for `LineFilters` only matches two exact `LineFilter`, but I think it is supposed to match n-`LineFilter`.
=> Grammar: Fix `LineFilters` to match multiple filters

CHANGELOG.md, package-lock.json, package.json, tools/tree-viz.html
Please take care of releasing this if you find it useful.
=> Chore: Bump lezer

tools/tree-viz.html
the `tree-viz.html` example uses the `unpkg.com` javascript-cdn, but it is very slow.
i looked at the list of CDNs offered at https://yarnpkg.com/package/@lezer/common , and there was `jsDelivr`, and it seems to work a lot faster, so i switched to it.
=> switch js cdn

test/expression.txt
This is related to https://github.com/grafana/lezer-logql/pull/9/files where we forgotten to update tests. I am not updating version as it doesn't have impact on users and can be included in the next user-changing release.
=> LogQL: Fix tests with `LineFilters`

README.md, package-lock.json, package.json, src/logql.grammar, test/expression.txt, tools/tree-viz.html
Currently our grammar has incorrectly matched string in 3 cases:
- If the string has single quotes `'`. This is not valid in LogQL.
- If the string with quotes `"` didn't have closing `"` (more info: https://discuss.codemirror.net/t/trying-to-understand-lezer-grammar-for-string/2264)
- If the string with back-tick \` didn't have closing \` (more info: https://discuss.codemirror.net/t/trying-to-understand-lezer-grammar-for-string/2264)
We are fixing this in this PR and adding tests.
=> Logql: Fix grammar for `String`

package-lock.json, package.json, src/logql.grammar, test/expression.txt, tools/tree-viz.html
As shown in this issue https://github.com/grafana/grafana/issues/54448 we are facing problems when parsing queries with errors. With the lezer-common update, lezer will not stop parsing until a known element is found or the end of the string. 
When parsing an empty stream selector `{}` followed by an unknown duration `[$__interval]` this resulted in unwanted behavior - e.g. when adding ad-hoc queries.
To overcome this for now, I added `$__interval` and `$__interval_ms` as known elements to the parser named as `DurationVariable`.
=> Grammar: Add `DurationVariable`

.github/workflows/publish-npm.yml, CHANGELOG.md, package-lock.json, package.json
We decided to release version `0.1.0`. A version `0.0.19` will follow, which will break the compatibility with `0.1.x`.
Reasoning for this:
- The dependency `"@lezer/lr": "^1.0.0"`, which is used in version `0.1.0` of this plugin, is incompatible to versions before.
=> Chore: Upgrade the main package to `0.1.0`

package-lock.json, package.json, src/logql.grammar, test/expression.txt, tools/tree-viz.html
There is a new Range operation - rate_counter. This PR adds it into a grammar. https://grafana.com/docs/loki/latest/logql/metric_queries/#unwrapped-range-aggregations
=> Grammar: Add `RateCounter`

package-lock.json, package.json, src/logql.grammar, src/tokens.js, test/expression.txt
This PR adds support to the DISTINCT filter expression added in https://github.com/grafana/loki/pull/8662
Examples:
```
{app="order"} | json | distinct id
```
```
{app="order"} | json | distinct id, time
```
Generated tree:
Part of https://github.com/grafana/grafana/issues/68170
=> Grammar: add distinct filter support

package-lock.json, package.json, src/logql.grammar, test/expression.txt
replace `Offset` with `OffsetExpr`.
lezer was expecting the wrong node therefore throwing errors with valid queries.
**Before & After:**
=> LogRangeExpr: Fix incorrect offset node

package.json
the **publish-npm** workflow is failing with `sh: 1: husky: not found`.
this is because husky is a dev dependency but the workflow only installs production dependencies.
this workaround stems from the following: https://github.com/typicode/husky/issues/914#issuecomment-1376981862
how this works:
- if husky exists in node_modules then we can run the scrip and it wont fail.
- if it doesn't exist (package not installed) we do nothing.
=> Fix npm publish workflow

package.json
Reverts grafana/lezer-logql#36
this bump was to trigger the workflow which still failed to publish, we can revert this so we don't skip many unnecessary versions.
=> Revert "Bump package version"

package.json
> first we merge #37 to revert back to 0.1.6, we then merge this that will build and release to 0.1.7
the issue we had was `prepare` we being called in the background of `npm publish...` this was then making the workflow fail because husky was not installed.
this changes the script to `postinstall` that still runs after `npn install` but doesnt get triggerd in the build and publish workflow
https://docs.npmjs.com/cli/v9/using-npm/scripts#npm-install
=> Replace prepare script with postinstall

src/formatter/metrics.js, src/formatter/utils.js
**Before:**
```
src/parser.js, src/exports.js → ./dist/index.cjs, ./dist/index.es.js...
(!) Circular dependency
src/formatter/formatter.js -> src/formatter/metrics.js -> src/formatter/formatter.js
created ./dist/index.cjs, ./dist/index.es.js in 80ms
```
**After:**
```
src/parser.js, src/exports.js → ./dist/index.cjs, ./dist/index.es.js...
created ./dist/index.cjs, ./dist/index.es.js in 77ms
```
=> Fix circular dependencies

package.json
> we only want to merge this after #39 so that fix is also included in the build
currently if you try to install `@grafana/lezer-logql@0.1.7` you will receive an error. this is caused by using "postinstall" instead of "prepare".
`One word of caution, use the "postinstall" hook only if you're not publishing your project on npm, else your users will get errors when trying to install your module.` https://github.com/typicode/husky/issues/227#issuecomment-361779926
=> Fix husky error when installing lezer-logql as dependency 

package.json
the last build/publish didn't work, this reverts the package back to 0.1.7 to we can retry the release.
=> Revert back to version 0.1.7

.husky/pre-commit, package-lock.json, package.json
husky was causing many problems when it comes to releasing a new version of lezer-logql.
our last plan was to just remove it so we can release a new version an be unblocked.
=> Remove husky pre-commit

package-lock.json, package.json, src/logql.grammar, src/tokens.js, test/expression.txt
Part of https://github.com/grafana/grafana/issues/70187 
While working on `drop` I noticed that in [LogQL grammar](https://github.com/grafana/loki/blob/main/pkg/logql/syntax/expr.y) another similar operations was added - `keep` so I implemented both. 
It follows the same grammar patterns as https://github.com/grafana/loki/blob/main/pkg/logql/syntax/expr.y.
=> Grammar: Add `drop` and `keep` operations

CHANGELOG.md, package-lock.json, package.json, src/logql.grammar, src/tokens.js, test/expression.txt
Adding support to `sort` and `sort_desc` for proper query handling, validation, and syntax highlighting.
Reference: https://github.com/grafana/loki/blob/main/pkg/logql/syntax/expr.y
LogQL part of https://github.com/grafana/grafana/issues/70882
Trees before:
Trees after:
=> LogQL: add sort and sort_desc support

test/expression.txt
I noticed that currently there are no tests for IP filter. In the next PR I am going to do a slight refactor to IP filter, so before doing so, I wanted to add tests to make it easier to review.
=> IP filter: Add tests

CHANGELOG.md, package.json, src/formatter/logs.js, src/logql.grammar, test/expression.txt, test/format.test.js
Mirrors https://github.com/grafana/loki/pull/13091
Adds negative number support to the LogQL parser.
* Works for both ints and floats.
* Negative durations are already supported.
* Negative bytes are not supported because the humanize library does not support them
=> feat: Support negative numbers in LogQL

package.json
Packages that declare themselves as ES modules (`"type": "module"` in package.json) that also include an `exports` property must declare a `types` property otherwise Typescript cannot find the types when typescripts `"moduleResolution": "bundler"` is set. Checking against [are the types wrong](https://arethetypeswrong.github.io/?p=%40grafana%2Flezer-logql%400.2.4) asserts that types cannot be found for anything above node10. An example of the error can be seen below:
=> Fix: exports must declare types for node16+

CHANGELOG.md, package-lock.json, package.json, src/logql.grammar, test/expression.txt
Enables support for parsing LogQL expression with pattern match line filters such as:
```
{ app="foobar" }  |> "I <_>"| json
```
and
```
{ app="foobar" }  !> "I <_>"| json
```
=> Add support for pattern match/not-match line filters

CHANGELOG.md, package-lock.json, package.json, src/logql.grammar, test/expression.txt, tools/tree-viz.local.html
`10.2s` creates an Error even though it is valid:
With this change, `10.2s` is correctly parsed as `Duration`:
Also adds a `local` script which can be used to start the tree-viz with the local build.
Fixes https://github.com/grafana/lezer-logql/issues/65
=> fix: allow floats to be used as duration and bytes
